# Generated by Django 4.2.7 on 2023-11-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
