# Generated by Django 4.2.7 on 2023-11-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_game_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='Shop.category'),
        ),
    ]
