# Generated by Django 4.2.7 on 2023-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_game_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='Shop.game'),
        ),
    ]
