# Generated by Django 4.2.7 on 2023-12-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_category_games'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
