# Generated by Django 4.2.7 on 2024-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_personaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='local_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
