# Generated by Django 4.2.7 on 2024-01-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_personaldata_local_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='local_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
