# Generated by Django 4.2.7 on 2024-01-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_alter_personaldata_local_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=255)),
                ('local_number', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Shop.deliveryaddress'),
        ),
    ]
