# Generated by Django 4.2.7 on 2024-01-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_payment_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='website_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(upload_to='website_images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Shop.delivery'),
        ),
    ]
