# Generated by Django 4.2.7 on 2024-01-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_delivery_alter_payment_image_order_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Delivery'},
        ),
    ]
