# Generated by Django 4.2.7 on 2024-01-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_alter_delivery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
