# Generated by Django 4.2.7 on 2024-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_alter_delivery_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'verbose_name': 'DeliveryAddress', 'verbose_name_plural': 'DeliveryAddress'},
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='e_mail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
