# Generated by Django 4.2.7 on 2024-01-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_alter_deliveryaddress_options_deliveryaddress_e_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, through='Shop.OrderItem', to='Shop.game'),
        ),
    ]
