# Generated by Django 4.2.7 on 2024-01-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_alter_order_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
